import subprocess
import sys
import argparse
import re

def run_command(command):
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {' '.join(command)}")
        print(f"Stderr: {e.stderr}")
        return None

def get_current_branch():
    return run_command(["git", "branch", "--show-current"])

def main():
    parser = argparse.ArgumentParser(description="Submit work: Commit, Push, and Create PR.")
    parser.add_argument("-m", "--message", help="Commit message")
    args = parser.parse_args()

    branch = get_current_branch()
    if not branch or branch == "main":
        print("Error: You must be on a feature branch to submit work.")
        sys.exit(1)

    # 1. Stage and Commit if there are changes
    status = run_command(["git", "status", "--short"])
    if status:
        msg = args.message or input(f"Enter commit message for branch {branch}: ")
        if not msg:
            print("Commit message required.")
            sys.exit(1)
        print("Staging and committing changes...")
        run_command(["git", "add", "."])
        run_command(["git", "commit", "-m", msg])
    else:
        print("No changes to commit.")

    # 2. Push branch
    print(f"Pushing {branch} to origin...")
    run_command(["git", "push", "-u", "origin", branch])

    # 3. Create PR
    print("Creating Pull Request...")
    # Attempt to extract issue number from branch name (e.g., feature/123-slug or bug/123-slug)
    issue_match = re.search(r'/(\d+)-', branch)
    body = "This PR was automatically generated by the Git Workflow Lifecycle skill."
    if issue_match:
        issue_num = issue_match.group(1)
        body += f"\n\nCloses #{issue_num}"

    pr_command = [
        "gh", "pr", "create",
        "--fill", # Use commit info for title and body
        "--body", body
    ]
    
    pr_url = run_command(pr_command)
    if pr_url:
        print(f"Successfully submitted work! PR URL: {pr_url}")
    else:
        # If --fill fails (e.g. no commits), try a manual title
        title = branch.split('/')[-1].replace('-', ' ').capitalize()
        pr_url = run_command(["gh", "pr", "create", "--title", title, "--body", body])
        if pr_url:
            print(f"Successfully submitted work! PR URL: {pr_url}")

if __name__ == "__main__":
    main()
