package scaffold

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type DeckOptions struct {
	Name      string
	TargetDir string
}

func CreateDeck(opts DeckOptions) error {
	if opts.Name == "" {
		return errors.New("deck name is required")
	}
	if opts.TargetDir == "" {
		return errors.New("target directory is required")
	}

	targetDir, err := filepath.Abs(opts.TargetDir)
	if err != nil {
		return fmt.Errorf("resolve target directory: %w", err)
	}

	files := map[string]string{
		"margo.yaml": scaffoldConfig(opts.Name),
		filepath.Join("slides", "01-title", "index.md"):              slideTitle(opts.Name),
		filepath.Join("slides", "02-why", "index.md"):                slideWhy(),
		filepath.Join("slides", "03-section", "index.md"):            slideSection(),
		filepath.Join("slides", "04-customer-story", "index.md"):     slideCustomerStory(),
		filepath.Join("slides", "05-closing", "index.md"):            slideClosing(),
		filepath.Join("archetypes", "default", "archetype.yaml"):     defaultArchetypeMetadata(),
		filepath.Join("archetypes", "title", "archetype.yaml"):       titleArchetypeMetadata(),
		filepath.Join("archetypes", "section", "archetype.yaml"):     sectionArchetypeMetadata(),
		filepath.Join("archetypes", "agenda", "archetype.yaml"):      agendaArchetypeMetadata(),
		filepath.Join("archetypes", "image", "archetype.yaml"):       imageArchetypeMetadata(),
		filepath.Join("archetypes", "two-column", "archetype.yaml"):  twoColumnArchetypeMetadata(),
		filepath.Join("archetypes", "media-right", "archetype.yaml"): mediaRightArchetypeMetadata(),
		filepath.Join("archetypes", "media-left", "archetype.yaml"):  mediaLeftArchetypeMetadata(),
		filepath.Join("archetypes", "quote", "archetype.yaml"):       quoteArchetypeMetadata(),
		filepath.Join("archetypes", "metric", "archetype.yaml"):      metricArchetypeMetadata(),
		filepath.Join("archetypes", "closing", "archetype.yaml"):     closingArchetypeMetadata(),
		filepath.Join("shortcodes", "eyebrow.html"):                  defaultDeckEyebrowShortcode(),
		filepath.Join("assets", "company-logo.svg"):                  starterDeckLogoAsset(),
		filepath.Join("assets", "shared-grid.svg"):                   starterDeckGridAsset(),
	}
	for path, content := range ThemeFiles("default", true) {
		files[path] = content
	}

	dirs := []string{
		"assets",
		filepath.Join("layouts"),
		filepath.Join("slides"),
		filepath.Join("themes"),
		filepath.Join("archetypes"),
		filepath.Join("shortcodes"),
	}

	if err := ensureCreatable(targetDir, files); err != nil {
		return err
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(targetDir, dir), 0o755); err != nil {
			return fmt.Errorf("create directory %q: %w", dir, err)
		}
	}

	for relativePath, content := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("create parent directory for %q: %w", relativePath, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %q: %w", relativePath, err)
		}
	}

	return nil
}

func ensureCreatable(targetDir string, files map[string]string) error {
	if info, err := os.Stat(targetDir); err == nil {
		if !info.IsDir() {
			return fmt.Errorf("target path exists and is not a directory: %s", targetDir)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat target directory %q: %w", targetDir, err)
	}

	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return fmt.Errorf("create target directory %q: %w", targetDir, err)
	}

	for relativePath := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if _, err := os.Stat(fullPath); err == nil {
			return fmt.Errorf("target file already exists: %s", fullPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat target file %q: %w", fullPath, err)
		}
	}

	return nil
}

func scaffoldConfig(deckName string) string {
	return fmt.Sprintf(`version: 1

deck:
  title: %s
  description: Starter deck generated by margo
  language: en
  logo: assets/company-logo.svg
  footer: Internal Strategy Review

theme:
  name: default
  color_mode: light
  typography: editorial
  accent_color: "#8f6f33"

outputs:
  html: true
  pdf: true
`, yamlString(deckName))
}

func slideTitle(deckName string) string {
	return fmt.Sprintf(`---
title: %s
order: 1
layout: title
---

# %s

Build beautiful slides from Markdown.

From scaffold to a shareable deck with themes, layouts, assets, and shortcodes.
`, yamlString(deckName), yamlString(deckName))
}

func slideWhy() string {
	return `---
title: Why Margo
order: 2
layout: content
---

{{< eyebrow label="Why this exists" />}}

- Markdown-first authoring
- Hugo-like project structure
- HTML-first output with PDF next

{{< callout tone="info" >}}
Theme-provided shortcodes make expressive slides possible without abandoning Markdown.
{{< /callout >}}

{{< columns >}}
{{< column >}}
### Authoring

- Markdown
- Front matter
- Archetypes
{{< /column >}}
{{< column >}}
### Output

- HTML first
- PDF next
- PPTX later
{{< /column >}}
{{< /columns >}}

{{< stat value="20" label="Slides" detail="A reasonably sized deck should still feel fast." />}}

![Shared brand texture](assets/shared-grid.svg)
`
}

func slideSection() string {
	return `---
title: Product Story
order: 3
layout: section
type: section
section: Product Story
---

# Product Story
`
}

func slideCustomerStory() string {
	return `---
title: Customer Story
order: 4
layout: media-right
type: media-right
section: Product Story
image_hints:
  fit: cover
  position: center
---

![Shared brand texture](assets/shared-grid.svg)

## Customer Story

- Use shared assets without leaving the deck model
- Mix structure and presentation with theme-owned layouts
- Keep the authoring flow Markdown-first

{{< callout tone="info" >}}
This slide demonstrates a media-oriented layout using a shared deck asset.
{{< /callout >}}
`
}

func slideClosing() string {
	return `---
title: Closing
order: 5
layout: closing
type: closing
---

# Build, theme, publish

Use this starter deck as a base, then replace content slide by slide.
`
}

func defaultArchetypeMetadata() string {
	return `name: default
description: Default slide archetype
default_layout: content
default_type: basic
`
}

func sectionArchetypeMetadata() string {
	return `name: section
description: Explicit section divider slide
default_layout: section
default_type: section
`
}

func titleArchetypeMetadata() string {
	return `name: title
description: Title or opening slide
default_layout: title
default_type: title
`
}

func agendaArchetypeMetadata() string {
	return `name: agenda
description: Agenda slide with ordered talking points
default_layout: agenda
default_type: agenda
`
}

func quoteArchetypeMetadata() string {
	return `name: quote
description: Quote slide with attribution
default_layout: quote
default_type: quote
`
}

func imageArchetypeMetadata() string {
	return `name: image
description: Visual-first slide with supporting copy
default_layout: image
default_type: image
`
}

func twoColumnArchetypeMetadata() string {
	return `name: two-column
description: Split content into two columns
default_layout: two-column
default_type: two-column
`
}

func mediaRightArchetypeMetadata() string {
	return `name: media-right
description: Image on the right with supporting content on the left
default_layout: media-right
default_type: media-right
`
}

func mediaLeftArchetypeMetadata() string {
	return `name: media-left
description: Image on the left with supporting content on the right
default_layout: media-left
default_type: media-left
`
}

func metricArchetypeMetadata() string {
	return `name: metric
description: Single key metric or KPI slide
default_layout: metric
default_type: metric
`
}

func closingArchetypeMetadata() string {
	return `name: closing
description: Closing or thank-you slide
default_layout: closing
default_type: closing
`
}

func defaultThemeMetadata() string {
	return `name: default
version: 0.1.0
description: Default Margo starter theme
config_options:
  - name: color_mode
    type: string
    description: Light or dark presentation mode
    default: light
    values:
      - light
      - dark
  - name: typography
    type: string
    description: Typography preset for deck tone
    default: editorial
    values:
      - editorial
      - executive
  - name: accent_color
    type: string
    description: Accent color used for emphasis
    default: "#8f6f33"
`
}

func ThemeFiles(themeName string, includeStyles bool) map[string]string {
	files := map[string]string{
		filepath.Join("themes", themeName, "theme.yaml"):                        defaultThemeMetadataWithName(themeName),
		filepath.Join("themes", themeName, "layouts", "deck.html"):              defaultThemeDeckLayout(),
		filepath.Join("themes", themeName, "layouts", "print-deck.html"):        defaultThemePrintDeckLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-agenda.html"):      defaultThemeAgendaLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-closing.html"):     defaultThemeClosingLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-default.html"):     defaultThemeSlideLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-image.html"):       defaultThemeImageLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-media-left.html"):  defaultThemeMediaLeftLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-media-right.html"): defaultThemeMediaRightLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-metric.html"):      defaultThemeMetricLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-quote.html"):       defaultThemeQuoteLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-section.html"):     defaultThemeSectionLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-title.html"):       defaultThemeTitleLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-two-column.html"):  defaultThemeTwoColumnLayout(),
		filepath.Join("themes", themeName, "partials", "deck-footer.html"):      defaultThemeDeckFooterPartial(),
		filepath.Join("themes", themeName, "partials", "deck-logo.html"):        defaultThemeDeckLogoPartial(),
		filepath.Join("themes", themeName, "shortcodes", "callout.html"):        defaultThemeCalloutShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "column.html"):         defaultThemeColumnShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "columns.html"):        defaultThemeColumnsShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "figure.html"):         defaultThemeFigureShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "github-repo.html"):    defaultThemeGitHubRepoShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "mermaid.html"):        defaultThemeMermaidShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "stat.html"):           defaultThemeStatShortcode(),
		filepath.Join("themes", themeName, "shortcodes", "video.html"):          defaultThemeVideoShortcode(),
	}
	if includeStyles {
		files[filepath.Join("themes", themeName, "assets", "theme.css")] = defaultThemeStyles()
	}
	return files
}

func defaultThemeMetadataWithName(themeName string) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0
description: Default Margo starter theme
config_options:
  - name: color_mode
    type: string
    description: Light or dark presentation mode
    default: light
    values:
      - light
      - dark
  - name: typography
    type: string
    description: Typography preset for deck tone
    default: editorial
    values:
      - editorial
      - executive
  - name: accent_color
    type: string
    description: Accent color used for emphasis
    default: "#8f6f33"
`, yamlString(themeName))
}

func defaultDeckEyebrowShortcode() string {
	return `<div class="section-meta">{{ index .Params "label" }}</div>
`
}

func starterDeckLogoAsset() string {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="220" height="64" viewBox="0 0 220 64" fill="none">
  <rect width="220" height="64" rx="18" fill="#F3E6C9"/>
  <path d="M28 44V20h7l8 12 8-12h7v24h-7V31l-8 11-8-11v13h-7z" fill="#1C1A17"/>
  <path d="M74 44V20h7v24h-7zm11.5 0V20h9.5c7.8 0 13 4.7 13 12s-5.2 12-13 12H85.5zm7-6h2.2c4.2 0 6.8-2.1 6.8-6s-2.6-6-6.8-6h-2.2v12z" fill="#1C1A17"/>
  <path d="M119 44V20h19v6h-12v3h11v5.7h-11V38h12.3v6H119z" fill="#1C1A17"/>
  <path d="M149 44V20h7l11 14.1V20h7v24h-6.6L156 29.3V44h-7z" fill="#1C1A17"/>
  <path d="M186.5 44V26h-7v-6h21v6h-7v18h-7z" fill="#1C1A17"/>
</svg>
`
}

func starterDeckGridAsset() string {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720" fill="none">
  <rect width="1280" height="720" rx="40" fill="#EDE4D3"/>
  <g opacity="0.55" stroke="#8F6F33" stroke-width="2">
    <path d="M80 160H1200"/>
    <path d="M80 300H1200"/>
    <path d="M80 440H1200"/>
    <path d="M80 580H1200"/>
    <path d="M220 80V640"/>
    <path d="M430 80V640"/>
    <path d="M640 80V640"/>
    <path d="M850 80V640"/>
    <path d="M1060 80V640"/>
  </g>
  <circle cx="220" cy="160" r="24" fill="#8F6F33"/>
  <circle cx="640" cy="300" r="24" fill="#1C1A17"/>
  <circle cx="1060" cy="440" r="24" fill="#8F6F33"/>
  <path d="M220 160L640 300L1060 440" stroke="#1C1A17" stroke-width="8" stroke-linecap="round"/>
</svg>
`
}

func defaultThemeCalloutShortcode() string {
	return `<div class="callout callout-{{ index .Params "tone" }}">
  {{ .Inner }}
</div>
`
}

func defaultThemeColumnsShortcode() string {
	return `<div class="shortcode-columns">
  {{ .Inner }}
</div>
`
}

func defaultThemeColumnShortcode() string {
	return `<div class="shortcode-column">
  {{ .Inner }}
</div>
`
}

func defaultThemeStatShortcode() string {
	return `<div class="shortcode-stat">
  <div class="shortcode-stat-value">{{ index .Params "value" }}</div>
  <div class="shortcode-stat-label">{{ index .Params "label" }}</div>
  {{ with index .Params "detail" }}<div class="shortcode-stat-detail">{{ . }}</div>{{ end }}
</div>
`
}

func defaultThemeFigureShortcode() string {
	return `{{ validateNoInner .Name .Inner }}{{ validateParams .Name .Params "src" "alt" "caption" "class" "width" "position" "fit" "link" "credit" }}{{ $src := assetRefStrict (requiredParam .Params "src") }}{{ $alt := requiredParam .Params "alt" }}{{ $fit := optionalParamOneOf .Params "fit" "contain" "cover" }}{{ $link := optionalParam .Params "link" }}{{ $width := optionalParam .Params "width" }}{{ $position := optionalParam .Params "position" }}{{ $caption := optionalParam .Params "caption" }}{{ $credit := optionalParam .Params "credit" }}{{ $extraClass := optionalParam .Params "class" }}<figure class="shortcode-figure{{ if $fit }} shortcode-figure-fit-{{ $fit }}{{ end }}{{ if $extraClass }} {{ $extraClass }}{{ end }}"{{ if $width }} style="--shortcode-figure-width: {{ $width }};"{{ end }}>{{ if $link }}<a class="shortcode-figure-link" href="{{ $link }}">{{ end }}<img class="shortcode-figure-image" src="{{ $src }}" alt="{{ $alt }}"{{ if $position }} style="object-position: {{ $position }};"{{ end }}>{{ if $link }}</a>{{ end }}{{ if or $caption $credit }}<figcaption class="shortcode-figure-caption">{{ if $caption }}<span>{{ $caption }}</span>{{ end }}{{ if $credit }}<span class="shortcode-figure-credit">{{ $credit }}</span>{{ end }}</figcaption>{{ end }}</figure>
`
}

func defaultThemeGitHubRepoShortcode() string {
	return `{{ validateNoInner .Name .Inner }}{{ validateParams .Name .Params "repo" "caption" "class" }}{{ $repo := mustMatch .Name (requiredParam .Params "repo") "repo" "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$" }}{{ $caption := optionalParam .Params "caption" }}{{ $extraClass := optionalParam .Params "class" }}{{ $url := printf "https://github.com/%s" $repo }}<figure class="shortcode-github-repo{{ if $extraClass }} {{ $extraClass }}{{ end }}"><a class="shortcode-github-repo-card" href="{{ $url }}"><div class="shortcode-github-repo-label">GitHub Repo</div><div class="shortcode-github-repo-name">{{ $repo }}</div><div class="shortcode-github-repo-url">{{ $url }}</div></a>{{ if $caption }}<figcaption class="shortcode-github-repo-caption">{{ $caption }}</figcaption>{{ end }}</figure>
`
}

func defaultThemeMermaidShortcode() string {
	return `{{ requiredInner .Name .Inner }}{{ validateParams .Name .Params "caption" "align" "class" }}{{ $align := optionalParamOneOf .Params "align" "left" "center" "right" }}{{ $caption := optionalParam .Params "caption" }}{{ $extraClass := optionalParam .Params "class" }}<figure class="shortcode-mermaid{{ if $align }} shortcode-mermaid-align-{{ $align }}{{ else }} shortcode-mermaid-align-center{{ end }}{{ if $extraClass }} {{ $extraClass }}{{ end }}"><div class="shortcode-mermaid-render" aria-hidden="true"></div><pre class="shortcode-mermaid-definition">{{ .Inner }}</pre>{{ if $caption }}<figcaption class="shortcode-mermaid-caption">{{ $caption }}</figcaption>{{ end }}</figure>
`
}

func defaultThemeVideoShortcode() string {
	return `<figure class="shortcode-video">
  <video controls preload="metadata"{{ with index .Params "poster" }} poster="{{ assetRef . }}"{{ end }}>
    <source src="{{ assetRef (index .Params "src") }}">
  </video>
  {{ with index .Params "caption" }}<figcaption>{{ . }}</figcaption>{{ end }}
</figure>
`
}

func defaultThemeDeckLogoPartial() string {
	return `{{ $root := .Root }}{{ $slide := .Slide }}{{ if and (or $root.DeckLogo.Text $root.DeckLogo.ImageSrc) (not $slide.HideLogo) }}<div class="deck-logo">{{ if $root.DeckLogo.IsImage }}<img src="{{ $root.DeckLogo.ImageSrc }}" alt="{{ $root.Deck.Title }} logo">{{ else }}{{ $root.DeckLogo.Text }}{{ end }}</div>{{ end }}
`
}

func defaultThemeDeckFooterPartial() string {
	return `{{ $slide := .Slide }}{{ if and $slide.ResolvedFooterText (not $slide.HideFooter) }}<div class="deck-footer">{{ $slide.ResolvedFooterText }}</div>{{ end }}
`
}

func defaultThemeDeckLayout() string {
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ .Deck.Title }}</title>
  {{ .Snippets.Head }}
  <style>
    :root {
      color-scheme: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}dark{{ else }}light{{ end }};
      --accent: {{ themeOption .ThemeOptions "accent_color" "#8f6f33" }};
      --bg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#131617{{ else }}#f4f1ea{{ end }};
      --fg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#f3efe8{{ else }}#1c1a17{{ end }};
      --muted: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#a9b0ac{{ else }}#6d655c{{ end }};
      --card: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#1c2123{{ else }}#fffdf9{{ end }};
      --shadow: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}rgba(0, 0, 0, 0.28){{ else }}rgba(28, 26, 23, 0.12){{ end }};
    }
    body {
      margin: 0;
      font-family: {{ if eq (themeOption .ThemeOptions "typography" "editorial") "executive" }}"Avenir Next", "Helvetica Neue", sans-serif{{ else }}"Iowan Old Style", Georgia, serif{{ end }};
      background: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}linear-gradient(180deg, #0f1213 0%, #1a2022 100%){{ else }}linear-gradient(180deg, #ebe5d8 0%, #f7f3ea 100%){{ end }};
      color: var(--fg);
    }
    main {
      min-height: 100vh;
      min-height: 100svh;
      display: grid;
      place-items: center;
      padding: 24px;
      box-sizing: border-box;
    }
    .deck {
      width: min(1200px, 100%);
      aspect-ratio: 16 / 9;
      background: var(--card);
      box-shadow: 0 24px 80px var(--shadow);
      overflow: hidden;
      position: relative;
    }
    .slide {
      display: none;
      height: 100%;
      padding: 72px;
      box-sizing: border-box;
      position: relative;
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
    }
    .slide::before {
      content: "";
      position: absolute;
      inset: 0;
      background: var(--margo-background-overlay, transparent);
      opacity: var(--margo-background-opacity, 1);
      pointer-events: none;
    }
    .slide.active {
      display: block;
    }
    .slide > * {
      position: relative;
      z-index: 1;
    }
    .deck-logo {
      position: absolute;
      top: 24px;
      right: 28px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-height: 28px;
      font: 12px/1 sans-serif;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .deck-logo img {
      display: block;
      max-height: 28px;
      max-width: 140px;
      width: auto;
      height: auto;
      object-fit: contain;
    }
    .deck-footer {
      position: absolute;
      left: 72px;
      bottom: 28px;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .slide-meta {
      font-size: 14px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
      margin-bottom: 0;
    }
    .section-meta {
      margin-bottom: 0;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--accent);
    }
    .slide-shell {
      display: grid;
      grid-template-rows: auto auto minmax(0, 1fr);
      align-content: start;
      gap: 14px;
      height: 100%;
      min-width: 0;
    }
    .slide-body {
      min-width: 0;
    }
    .prose-body {
      max-width: 860px;
    }
    .content-slide .slide-body {
      align-self: start;
    }
    .title-slide {
      gap: 18px;
      align-content: end;
    }
    .title-stack {
      display: grid;
      gap: 18px;
      align-content: end;
      max-width: 920px;
      padding-bottom: 24px;
    }
    .title-stack h1 {
      font-size: 88px;
      line-height: 0.94;
      letter-spacing: -0.04em;
      max-width: 9ch;
    }
    .title-stack p {
      max-width: 24ch;
      font-size: 27px;
      line-height: 1.28;
      color: var(--muted);
    }
    .section-slide {
      align-content: center;
      gap: 20px;
    }
    .section-stack {
      display: grid;
      align-content: center;
      gap: 18px;
      max-width: 760px;
    }
    .section-stack::before {
      content: "";
      width: 92px;
      height: 4px;
      border-radius: 999px;
      background: var(--accent);
      box-shadow: 0 10px 24px color-mix(in srgb, var(--accent) 28%, transparent);
    }
    .section-stack h1 {
      font-size: 84px;
      line-height: 0.94;
      letter-spacing: -0.04em;
    }
    .draft-badge {
      display: inline-block;
      margin-bottom: 18px;
      padding: 6px 10px;
      border: 1px solid currentColor;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #8a3b12;
      background: #f7dcc9;
    }
    .slide-body h1,
    .slide-body h2,
    .slide-body h3,
    .slide-body p,
    .slide-body ul,
    .slide-body ol,
    .slide-body blockquote,
    .slide-body figure {
      margin: 0 0 16px;
    }
    .slide-body h1 {
      font-size: 64px;
      line-height: 0.98;
      letter-spacing: -0.035em;
    }
    .slide-body h2 {
      font-size: 34px;
      line-height: 1.1;
      letter-spacing: -0.025em;
    }
    .slide-body h3 {
      font-size: 22px;
      line-height: 1.2;
      letter-spacing: -0.015em;
      font-family: "Avenir Next", "Helvetica Neue", sans-serif;
    }
    .slide-body p,
    .slide-body li {
      font-size: 22px;
      line-height: 1.42;
    }
    .slide-body ul {
      padding-left: 24px;
    }
    .slide-body ol {
      padding-left: 28px;
    }
    .slide-body strong {
      color: color-mix(in srgb, var(--fg) 82%, var(--accent));
    }
    .slide-body img {
      max-width: 100%;
      height: auto;
      border-radius: 18px;
      object-position: var(--margo-image-position, center);
    }
    .slide.image-fit-contain .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: contain;
    }
    .slide.image-fit-cover .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: cover;
    }
    .image-caption {
      margin-top: 14px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .callout {
      margin: 24px 0;
      padding: 18px 20px;
      border-radius: 18px;
      background: color-mix(in srgb, var(--accent) 10%, var(--card));
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      box-shadow: 0 12px 30px rgba(0, 0, 0, 0.06);
    }
    .callout p:last-child {
      margin-bottom: 0;
    }
    .shortcode-columns {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
      margin: 28px 0;
    }
    .shortcode-column {
      padding: 18px 20px;
      border-radius: 18px;
      background: color-mix(in srgb, var(--card) 88%, var(--accent) 12%);
      border: 1px solid color-mix(in srgb, var(--accent) 14%, transparent);
    }
    .shortcode-column > :first-child {
      margin-top: 0;
    }
    .shortcode-stat {
      margin: 28px 0 0;
      padding: 22px 24px;
      border-radius: 22px;
      background: linear-gradient(180deg, color-mix(in srgb, var(--accent) 12%, transparent), color-mix(in srgb, var(--card) 92%, transparent));
      border: 1px solid color-mix(in srgb, var(--accent) 20%, transparent);
    }
    .shortcode-stat-value {
      font-size: 52px;
      line-height: 0.95;
      color: var(--accent);
      font-weight: 700;
    }
    .shortcode-stat-label {
      margin-top: 10px;
      font: 13px/1.2 sans-serif;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-stat-detail {
      margin-top: 10px;
      color: var(--fg);
    }
    .shortcode-figure {
      margin: 28px 0;
      max-width: min(100%, var(--shortcode-figure-width, 100%));
    }
    .shortcode-figure-link {
      display: block;
      color: inherit;
      text-decoration: none;
    }
    .shortcode-figure-image {
      display: block;
      width: 100%;
      max-height: 48vh;
      object-fit: contain;
      border-radius: 20px;
      box-shadow: 0 20px 48px var(--shadow);
      background: color-mix(in srgb, var(--card) 92%, transparent);
    }
    .shortcode-figure-fit-cover .shortcode-figure-image {
      object-fit: cover;
    }
    .shortcode-figure-fit-contain .shortcode-figure-image {
      object-fit: contain;
    }
    .shortcode-figure-caption {
      margin-top: 12px;
      display: grid;
      gap: 6px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-figure-credit {
      color: color-mix(in srgb, var(--muted) 88%, var(--fg));
    }
    .shortcode-video {
      margin: 28px 0;
    }
    .shortcode-video video {
      width: 100%;
      max-height: 48vh;
      border-radius: 20px;
      box-shadow: 0 20px 48px var(--shadow);
      background: #000;
    }
    .shortcode-video figcaption {
      margin-top: 12px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-github-repo {
      margin: 28px 0;
      max-width: min(100%, 32rem);
    }
    .shortcode-github-repo-card {
      display: grid;
      gap: 8px;
      padding: 20px 22px;
      border-radius: 22px;
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      background:
        radial-gradient(circle at top right, color-mix(in srgb, var(--accent) 18%, transparent), transparent 42%),
        color-mix(in srgb, var(--card) 95%, transparent);
      box-shadow: 0 20px 48px var(--shadow);
      color: inherit;
      text-decoration: none;
    }
    .shortcode-github-repo-card:hover,
    .shortcode-github-repo-card:focus-visible {
      transform: translateY(-1px);
      box-shadow: 0 24px 54px var(--shadow);
      outline: none;
    }
    .shortcode-github-repo-label {
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-github-repo-name {
      font-size: 28px;
      line-height: 1.08;
      letter-spacing: -0.03em;
      color: color-mix(in srgb, var(--fg) 88%, var(--accent));
    }
    .shortcode-github-repo-url {
      font: 14px/1.35 "SFMono-Regular", "Menlo", "Consolas", monospace;
      color: var(--muted);
      word-break: break-all;
    }
    .shortcode-github-repo-caption {
      margin-top: 12px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-mermaid {
      margin: 28px 0;
      display: grid;
      gap: 12px;
    }
    .shortcode-mermaid.shortcode-mermaid-align-center {
      justify-items: center;
    }
    .shortcode-mermaid.shortcode-mermaid-align-right {
      justify-items: end;
    }
    .shortcode-mermaid-render {
      display: none;
      width: min(100%, 860px);
      padding: 18px;
      border-radius: 20px;
      background: color-mix(in srgb, var(--card) 95%, transparent);
      box-shadow: 0 20px 48px var(--shadow);
      overflow: auto;
    }
    .shortcode-mermaid.is-rendered .shortcode-mermaid-render {
      display: block;
    }
    .shortcode-mermaid-render svg {
      display: block;
      width: 100%;
      height: auto;
    }
    .shortcode-mermaid-definition {
      width: min(100%, 860px);
      margin: 0;
      padding: 18px 20px;
      border-radius: 20px;
      background: color-mix(in srgb, var(--card) 92%, transparent);
      box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent);
      color: var(--fg);
      font: 15px/1.5 "SFMono-Regular", "Menlo", "Consolas", monospace;
      white-space: pre-wrap;
      overflow: auto;
    }
    .shortcode-mermaid.is-rendered .shortcode-mermaid-definition {
      display: none;
    }
    .shortcode-mermaid-caption {
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .agenda-slide ol {
      margin: 22px 0 0;
      padding-left: 28px;
      font-size: 28px;
      line-height: 1.45;
    }
    .agenda-slide li {
      margin-bottom: 14px;
      padding-left: 8px;
    }
    .image-slide {
      display: grid;
      align-content: start;
      height: 100%;
    }
    .image-shell {
      display: grid;
      gap: 20px;
      align-content: start;
    }
    .image-slide p:has(img) {
      margin: 0;
    }
    .image-slide img {
      width: 100%;
      max-height: 52vh;
      object-fit: cover;
      border-radius: 24px;
      box-shadow: 0 20px 48px var(--shadow);
    }
    .two-column-slide {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 40px;
      align-content: start;
      height: 100%;
    }
    .two-column-slide .column {
      min-width: 0;
      padding: 22px 24px;
      border-radius: 24px;
      background: color-mix(in srgb, var(--card) 90%, var(--accent) 10%);
      border: 1px solid color-mix(in srgb, var(--accent) 14%, transparent);
    }
    .two-column-slide .column > :first-child {
      margin-top: 0;
    }
    .media-split-slide {
      display: grid;
      grid-template-columns: minmax(0, 1.05fr) minmax(0, 0.95fr);
      gap: 36px;
      align-items: center;
      height: 100%;
    }
    .media-split-slide.media-left {
      grid-template-areas: "media content";
    }
    .media-split-slide.media-right {
      grid-template-areas: "content media";
    }
    .media-pane {
      grid-area: media;
      min-width: 0;
    }
    .content-pane {
      grid-area: content;
      min-width: 0;
    }
    .media-pane p {
      margin: 0;
    }
    .media-pane img {
      width: 100%;
      max-height: 58vh;
      object-fit: cover;
      border-radius: 26px;
      box-shadow: 0 24px 56px var(--shadow);
    }
    .content-pane > :first-child {
      margin-top: 0;
    }
    .content-pane > :last-child {
      margin-bottom: 0;
    }
    .quote-slide {
      display: grid;
      gap: 28px;
      align-content: center;
      height: 100%;
    }
    .quote-shell {
      max-width: 880px;
      padding: 24px 0;
    }
    .quote-slide blockquote {
      margin: 0;
      padding-left: 28px;
      border-left: 4px solid var(--accent);
      font-size: 42px;
      line-height: 1.2;
      color: var(--fg);
    }
    .quote-slide p:last-child {
      margin: 0;
      font: 16px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .metric-slide {
      display: grid;
      gap: 18px;
      align-content: center;
      height: 100%;
      text-align: center;
    }
    .metric-shell {
      padding: 40px 48px;
      border-radius: 28px;
      background: linear-gradient(180deg, color-mix(in srgb, var(--accent) 12%, transparent), color-mix(in srgb, var(--card) 96%, white 4%));
      border: 1px solid color-mix(in srgb, var(--accent) 24%, transparent);
      box-shadow: 0 24px 56px var(--shadow);
    }
    .metric-slide h1 {
      margin: 0;
      font-size: 132px;
      line-height: 0.95;
      color: var(--accent);
    }
    .metric-slide p {
      margin: 0;
    }
    .metric-slide p:first-of-type {
      font-size: 28px;
    }
    .metric-slide p:last-of-type {
      max-width: 560px;
      margin-inline: auto;
      color: var(--muted);
    }
    .closing-slide {
      display: grid;
      place-items: center;
      height: 100%;
      text-align: center;
    }
    .closing-shell {
      background:
        radial-gradient(circle at top, color-mix(in srgb, var(--accent) 18%, transparent), transparent 45%),
        linear-gradient(180deg, color-mix(in srgb, var(--card) 92%, white 8%), color-mix(in srgb, var(--card) 98%, white 2%));
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      border-radius: 28px;
      padding: 40px 42px;
      box-sizing: border-box;
      box-shadow: 0 24px 56px var(--shadow);
    }
    .closing-shell h1 {
      font-size: 72px;
      margin-bottom: 18px;
    }
    .closing-shell p {
      max-width: 540px;
      margin-inline: auto;
      color: var(--muted);
      font-size: 22px;
      line-height: 1.4;
    }
    .controls {
      position: absolute;
      right: 24px;
      bottom: 18px;
      color: var(--muted);
      font: 14px/1.2 sans-serif;
      display: flex;
      gap: 12px;
      align-items: center;
      z-index: 3;
    }
    .nav-hint {
      white-space: nowrap;
    }
    .pdf-export {
      border: 1px solid rgba(28, 26, 23, 0.18);
      background: rgba(255, 253, 249, 0.92);
      color: var(--fg);
      padding: 8px 12px;
      border-radius: 999px;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      cursor: pointer;
    }
    .pdf-export:hover {
      background: #fffdf9;
    }
    .slide-dots {
      position: absolute;
      left: 50%;
      bottom: 18px;
      transform: translateX(-50%);
      display: none;
      align-items: center;
      gap: 10px;
      padding: 10px 14px;
      border-radius: 999px;
      background: color-mix(in srgb, var(--card) 86%, transparent);
      box-shadow: 0 16px 36px var(--shadow);
      backdrop-filter: blur(16px);
      z-index: 3;
    }
    .slide-dot {
      width: 11px;
      height: 11px;
      border: 0;
      border-radius: 999px;
      padding: 0;
      background: color-mix(in srgb, var(--muted) 36%, transparent);
      cursor: pointer;
      transition: transform 160ms ease, background 160ms ease;
    }
    .slide-dot:hover,
    .slide-dot:focus-visible {
      background: color-mix(in srgb, var(--accent) 55%, var(--card));
      transform: scale(1.08);
      outline: none;
    }
    .slide-dot[aria-current="true"] {
      background: var(--accent);
      transform: scale(1.16);
    }
    @media (max-width: 900px) {
      body {
        background: var(--bg);
      }
      main {
        display: block;
        min-height: 100vh;
        min-height: 100svh;
        padding: 0;
      }
      .deck {
        width: 100%;
        min-height: 100vh;
        min-height: 100svh;
        aspect-ratio: auto;
        display: flex;
        overflow-x: auto;
        overflow-y: hidden;
        scroll-snap-type: x mandatory;
        scroll-behavior: smooth;
        overscroll-behavior-x: contain;
        background: transparent;
        box-shadow: none;
      }
      .deck::-webkit-scrollbar {
        display: none;
      }
      .slide {
        display: block;
        flex: 0 0 100%;
        width: 100%;
        min-height: 100vh;
        min-height: 100svh;
        height: auto;
        padding: 76px 24px 88px;
        scroll-snap-align: start;
      }
      .slide.active {
        display: block;
      }
      .slide-shell {
        gap: 12px;
      }
      .deck-logo {
        top: 18px;
        right: 20px;
      }
      .deck-footer {
        left: 24px;
        bottom: 26px;
      }
      .title-stack h1,
      .section-stack h1 {
        font-size: 52px;
      }
      .slide-body h1 {
        font-size: 42px;
      }
      .slide-body h2 {
        font-size: 28px;
      }
      .slide-body h3 {
        font-size: 20px;
      }
      .slide-body p,
      .slide-body li {
        font-size: 18px;
        line-height: 1.45;
      }
      .title-stack p {
        font-size: 22px;
      }
      .closing-shell {
        padding: 28px 24px;
      }
      .closing-shell h1 {
        font-size: 48px;
      }
      .closing-shell p {
        font-size: 18px;
      }
      .controls {
        position: fixed;
        right: 16px;
        left: 16px;
        bottom: 72px;
        justify-content: flex-end;
      }
      .nav-hint {
        display: none;
      }
      .slide-dots {
        position: fixed;
        display: inline-flex;
        bottom: 18px;
        max-width: calc(100% - 32px);
        overflow-x: auto;
      }
      .slide-dots::-webkit-scrollbar {
        display: none;
      }
      .prose-body,
      .title-stack,
      .section-stack {
        max-width: none;
      }
      .slide.image-fit-contain .slide-body img,
      .slide.image-fit-cover .slide-body img {
        max-height: 34vh;
      }
      .media-split-slide,
      .two-column-slide,
      .shortcode-columns {
        grid-template-columns: 1fr;
      }
    }
    @media print {
      @page {
        size: 13.333in 7.5in;
        margin: 0;
      }
      html, body {
        width: 100%;
        height: auto;
        margin: 0;
        padding: 0;
        background: #fff;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      main {
        display: block;
        min-height: auto;
        padding: 0;
      }
      .deck {
        width: 100%;
        aspect-ratio: auto;
        background: transparent;
        box-shadow: none;
      }
      .slide {
        display: block !important;
        width: 100%;
        min-height: 7.5in;
        height: 7.5in;
        break-after: page;
        page-break-after: always;
      }
      .slide:last-of-type {
        break-after: auto;
        page-break-after: auto;
      }
      .controls {
        display: none !important;
      }
    }
  </style>
</head>
<body>
  <main>
    <div class="deck">
      {{ $root := . }}
      {{ range $i, $slide := .Slides }}
      <section class="slide{{ if eq $i 0 }} active{{ end }}{{ if $slide.ImageHintClass }} {{ $slide.ImageHintClass }}{{ end }}"{{ if $slide.StyleAttr }} style="{{ $slide.StyleAttr }}"{{ end }}>
        {{ if $slide.IsDraft }}<div class="draft-badge">Draft</div>{{ end }}
        {{ template "deck-logo" (dict "Root" $root "Slide" $slide) }}
        {{ $slide.Body }}
        {{ if $slide.ImageCaption }}<div class="image-caption">{{ $slide.ImageCaption }}</div>{{ end }}
        {{ template "deck-footer" (dict "Root" $root "Slide" $slide) }}
      </section>
      {{ end }}
      <div class="controls">
        {{ if .PDFEnabled }}<button class="pdf-export" type="button" id="export-pdf">Export PDF</button>{{ end }}
        <span class="nav-hint">Use left/right arrow keys</span>
      </div>
      <div class="slide-dots" aria-label="Slide navigation">
        {{ range $i, $slide := .Slides }}
        <button class="slide-dot" type="button" data-slide-dot="{{ $i }}" aria-label="{{ if $slide.Title }}Go to slide: {{ $slide.Title }}{{ else }}Go to slide{{ end }}"{{ if eq $i 0 }} aria-current="true"{{ end }}></button>
        {{ end }}
      </div>
    </div>
  </main>
  <script>
    const deck = document.querySelector('.deck');
    const slides = Array.from(document.querySelectorAll('.slide'));
    const dots = Array.from(document.querySelectorAll('[data-slide-dot]'));
    const mobileQuery = window.matchMedia('(max-width: 900px)');
    let index = 0;
    const syncDots = () => {
      dots.forEach((dot, i) => {
        if (i === index) {
          dot.setAttribute('aria-current', 'true');
        } else {
          dot.removeAttribute('aria-current');
        }
      });
    };
    const show = (nextIndex) => {
      if (!slides.length) return;
      index = Math.max(0, Math.min(nextIndex, slides.length - 1));
      slides.forEach((slide, i) => slide.classList.toggle('active', i === index));
      syncDots();
      if (mobileQuery.matches) {
        slides[index].scrollIntoView({ behavior: 'smooth', inline: 'start', block: 'nearest' });
      }
    };
    const syncIndexFromScroll = () => {
      if (!mobileQuery.matches || !deck || !slides.length) return;
      const nextIndex = Math.round(deck.scrollLeft / Math.max(deck.clientWidth, 1));
      if (nextIndex !== index) {
        index = Math.max(0, Math.min(nextIndex, slides.length - 1));
        slides.forEach((slide, i) => slide.classList.toggle('active', i === index));
        syncDots();
      }
    };
    document.addEventListener('keydown', (event) => {
      if (mobileQuery.matches) return;
      if (event.key === 'ArrowRight' || event.key === 'PageDown') show(index + 1);
      if (event.key === 'ArrowLeft' || event.key === 'PageUp') show(index - 1);
    });
    dots.forEach((dot, dotIndex) => {
      dot.addEventListener('click', () => show(dotIndex));
    });
    if (deck) {
      deck.addEventListener('scroll', syncIndexFromScroll, { passive: true });
    }
    mobileQuery.addEventListener('change', () => {
      if (mobileQuery.matches) {
        slides[index]?.scrollIntoView({ block: 'nearest', inline: 'start' });
      } else {
        if (deck) {
          deck.scrollTo({ left: 0, top: 0 });
        }
        show(index);
      }
    });
    syncDots();
    const renderMermaidDiagrams = async () => {
      const diagrams = Array.from(document.querySelectorAll('.shortcode-mermaid'));
      if (!diagrams.length) return;
      try {
        const mermaidModule = await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs');
        const mermaid = mermaidModule.default;
        const mermaidTheme = getComputedStyle(document.documentElement).colorScheme === 'dark' ? 'dark' : 'default';
        mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', theme: mermaidTheme });
        for (const [diagramIndex, diagram] of diagrams.entries()) {
          const definition = diagram.querySelector('.shortcode-mermaid-definition')?.textContent?.trim();
          const target = diagram.querySelector('.shortcode-mermaid-render');
          if (!definition || !target) continue;
          const { svg } = await mermaid.render('margo-mermaid-' + diagramIndex, definition);
          target.innerHTML = svg;
          diagram.classList.add('is-rendered');
        }
      } catch (error) {
        console.warn('Mermaid render failed', error);
      }
    };
    renderMermaidDiagrams();
    const exportButton = document.getElementById('export-pdf');
    if (exportButton) {
      exportButton.addEventListener('click', async () => {
        try {
          const response = await fetch('/__margo/export/pdf', { method: 'POST' });
          const message = (await response.text()).trim();
          if (!response.ok) {
            throw new Error(message || 'PDF export failed');
          }
          window.alert(message || 'PDF export complete');
        } catch (error) {
          window.alert(error.message || 'PDF export failed');
        }
      });
    }
    let currentRevision = null;
    const checkRevision = async () => {
      try {
        const response = await fetch('/__margo/version', { cache: 'no-store' });
        const nextRevision = (await response.text()).trim();
        if (currentRevision === null) {
          currentRevision = nextRevision;
          return;
        }
        if (nextRevision !== currentRevision) {
          window.location.reload();
        }
      } catch (_) {}
    };
    setInterval(checkRevision, 1000);
    checkRevision();
  </script>
  {{ .Snippets.BodyEnd }}
</body>
</html>
`
}

func defaultThemePrintDeckLayout() string {
	return `<!doctype html>
<html lang="en" class="margo-print {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}color-mode-dark{{ else }}color-mode-light{{ end }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ .Deck.Title }}</title>
  {{ .Snippets.Head }}
  <style>
    :root {
      color-scheme: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}dark{{ else }}light{{ end }};
      --accent: {{ themeOption .ThemeOptions "accent_color" "#8f6f33" }};
      --bg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#131617{{ else }}#f4f1ea{{ end }};
      --fg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#f3efe8{{ else }}#1c1a17{{ end }};
      --muted: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#a9b0ac{{ else }}#6d655c{{ end }};
      --card: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#1c2123{{ else }}#fffdf9{{ end }};
      --shadow: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}rgba(0, 0, 0, 0.28){{ else }}rgba(28, 26, 23, 0.12){{ end }};
    }
    html, body {
      width: 100%;
      height: auto;
      margin: 0;
      padding: 0;
      background: #fff;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    body {
      font-family: {{ if eq (themeOption .ThemeOptions "typography" "editorial") "executive" }}"Avenir Next", "Helvetica Neue", sans-serif{{ else }}"Iowan Old Style", Georgia, serif{{ end }};
      color: var(--fg);
    }
    main {
      display: block;
      min-height: auto;
      padding: 0;
    }
    .deck {
      width: 100%;
      aspect-ratio: auto;
      background: transparent;
      box-shadow: none;
      overflow: hidden;
      position: relative;
    }
    .slide {
      display: block !important;
      width: 13.333in;
      min-height: 7.5in;
      height: 7.5in;
      padding: 72px;
      box-sizing: border-box;
      position: relative;
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
      break-after: page;
      page-break-after: always;
    }
    .slide:last-of-type {
      break-after: auto;
      page-break-after: auto;
    }
    .slide::before {
      content: "";
      position: absolute;
      inset: 0;
      background: var(--margo-background-overlay, transparent);
      opacity: var(--margo-background-opacity, 1);
      pointer-events: none;
    }
    .slide > * {
      position: relative;
      z-index: 1;
    }
    .deck-logo {
      position: absolute;
      top: 24px;
      right: 28px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-height: 28px;
      font: 12px/1 sans-serif;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .deck-logo img {
      display: block;
      max-height: 28px;
      max-width: 140px;
      width: auto;
      height: auto;
      object-fit: contain;
    }
    .deck-footer {
      position: absolute;
      left: 72px;
      bottom: 28px;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .slide-meta {
      font-size: 14px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
      margin-bottom: 0;
    }
    .section-meta {
      margin-bottom: 0;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--accent);
    }
    .slide-shell {
      display: grid;
      grid-template-rows: auto auto minmax(0, 1fr);
      align-content: start;
      gap: 14px;
      height: 100%;
      min-width: 0;
    }
    .slide-body {
      min-width: 0;
    }
    .prose-body {
      max-width: 860px;
    }
    .content-slide .slide-body {
      align-self: start;
    }
    .title-slide {
      gap: 18px;
      align-content: end;
    }
    .title-stack {
      display: grid;
      gap: 18px;
      align-content: end;
      max-width: 920px;
      padding-bottom: 24px;
    }
    .title-stack h1 {
      font-size: 88px;
      line-height: 0.94;
      letter-spacing: -0.04em;
      max-width: 9ch;
    }
    .title-stack p {
      max-width: 24ch;
      font-size: 27px;
      line-height: 1.28;
      color: var(--muted);
    }
    .section-slide {
      align-content: center;
      gap: 20px;
    }
    .section-stack {
      display: grid;
      align-content: center;
      gap: 18px;
      max-width: 760px;
    }
    .section-stack::before {
      content: "";
      width: 92px;
      height: 4px;
      border-radius: 999px;
      background: var(--accent);
      box-shadow: 0 10px 24px color-mix(in srgb, var(--accent) 28%, transparent);
    }
    .section-stack h1 {
      font-size: 84px;
      line-height: 0.94;
      letter-spacing: -0.04em;
    }
    .draft-badge {
      display: inline-block;
      margin-bottom: 18px;
      padding: 6px 10px;
      border: 1px solid currentColor;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #8a3b12;
      background: #f7dcc9;
    }
    .slide-body h1,
    .slide-body h2,
    .slide-body h3,
    .slide-body p,
    .slide-body ul,
    .slide-body ol,
    .slide-body blockquote,
    .slide-body figure {
      margin: 0 0 16px;
    }
    .slide-body h1 {
      font-size: 64px;
      line-height: 0.98;
      letter-spacing: -0.035em;
    }
    .slide-body h2 {
      font-size: 34px;
      line-height: 1.1;
      letter-spacing: -0.025em;
    }
    .slide-body h3 {
      font-size: 22px;
      line-height: 1.2;
      letter-spacing: -0.015em;
      font-family: "Avenir Next", "Helvetica Neue", sans-serif;
    }
    .slide-body p,
    .slide-body li {
      font-size: 22px;
      line-height: 1.42;
    }
    .slide-body ul {
      padding-left: 24px;
    }
    .slide-body ol {
      padding-left: 28px;
    }
    .slide-body strong {
      color: color-mix(in srgb, var(--fg) 82%, var(--accent));
    }
    .slide-body img {
      max-width: 100%;
      height: auto;
      border-radius: 18px;
      object-position: var(--margo-image-position, center);
    }
    .slide.image-fit-contain .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: contain;
    }
    .slide.image-fit-cover .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: cover;
    }
    .image-caption {
      margin-top: 14px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .callout {
      margin: 24px 0;
      padding: 18px 20px;
      border-radius: 18px;
      background: color-mix(in srgb, var(--accent) 10%, var(--card));
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      box-shadow: 0 12px 30px rgba(0, 0, 0, 0.06);
    }
    .callout p:last-child {
      margin-bottom: 0;
    }
    .shortcode-columns {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
      margin: 28px 0;
    }
    .shortcode-column {
      padding: 18px 20px;
      border-radius: 18px;
      background: color-mix(in srgb, var(--card) 88%, var(--accent) 12%);
      border: 1px solid color-mix(in srgb, var(--accent) 14%, transparent);
    }
    .shortcode-column > :first-child {
      margin-top: 0;
    }
    .shortcode-stat {
      margin: 28px 0 0;
      padding: 22px 24px;
      border-radius: 22px;
      background: linear-gradient(180deg, color-mix(in srgb, var(--accent) 12%, transparent), color-mix(in srgb, var(--card) 92%, transparent));
      border: 1px solid color-mix(in srgb, var(--accent) 20%, transparent);
    }
    .shortcode-stat-value {
      font-size: 52px;
      line-height: 0.95;
      color: var(--accent);
      font-weight: 700;
    }
    .shortcode-stat-label {
      margin-top: 10px;
      font: 13px/1.2 sans-serif;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-stat-detail {
      margin-top: 10px;
      color: var(--fg);
    }
    .shortcode-figure {
      margin: 28px 0;
      max-width: min(100%, var(--shortcode-figure-width, 100%));
    }
    .shortcode-figure-link {
      display: block;
      color: inherit;
      text-decoration: none;
    }
    .shortcode-figure-image {
      display: block;
      width: 100%;
      max-height: 48vh;
      object-fit: contain;
      border-radius: 20px;
      box-shadow: 0 20px 48px var(--shadow);
      background: color-mix(in srgb, var(--card) 92%, transparent);
    }
    .shortcode-figure-fit-cover .shortcode-figure-image {
      object-fit: cover;
    }
    .shortcode-figure-fit-contain .shortcode-figure-image {
      object-fit: contain;
    }
    .shortcode-figure-caption {
      margin-top: 12px;
      display: grid;
      gap: 6px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-figure-credit {
      color: color-mix(in srgb, var(--muted) 88%, var(--fg));
    }
    .shortcode-video {
      margin: 28px 0;
    }
    .shortcode-video video {
      width: 100%;
      max-height: 48vh;
      border-radius: 20px;
      box-shadow: 0 20px 48px var(--shadow);
      background: #000;
    }
    .shortcode-video figcaption {
      margin-top: 12px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-github-repo {
      margin: 28px 0;
      max-width: min(100%, 32rem);
    }
    .shortcode-github-repo-card {
      display: grid;
      gap: 8px;
      padding: 20px 22px;
      border-radius: 22px;
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      background:
        radial-gradient(circle at top right, color-mix(in srgb, var(--accent) 18%, transparent), transparent 42%),
        color-mix(in srgb, var(--card) 95%, transparent);
      box-shadow: 0 20px 48px var(--shadow);
      color: inherit;
      text-decoration: none;
    }
    .shortcode-github-repo-label {
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-github-repo-name {
      font-size: 28px;
      line-height: 1.08;
      letter-spacing: -0.03em;
      color: color-mix(in srgb, var(--fg) 88%, var(--accent));
    }
    .shortcode-github-repo-url {
      font: 14px/1.35 "SFMono-Regular", "Menlo", "Consolas", monospace;
      color: var(--muted);
      word-break: break-all;
    }
    .shortcode-github-repo-caption {
      margin-top: 12px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .shortcode-mermaid {
      margin: 28px 0;
      display: grid;
      gap: 12px;
    }
    .shortcode-mermaid.shortcode-mermaid-align-center {
      justify-items: center;
    }
    .shortcode-mermaid.shortcode-mermaid-align-right {
      justify-items: end;
    }
    .shortcode-mermaid-render {
      display: none;
      width: min(100%, 860px);
      padding: 18px;
      border-radius: 20px;
      background: color-mix(in srgb, var(--card) 95%, transparent);
      box-shadow: 0 20px 48px var(--shadow);
      overflow: auto;
    }
    .shortcode-mermaid.is-rendered .shortcode-mermaid-render {
      display: block;
    }
    .shortcode-mermaid-render svg {
      display: block;
      width: 100%;
      height: auto;
    }
    .shortcode-mermaid-definition {
      width: min(100%, 860px);
      margin: 0;
      padding: 18px 20px;
      border-radius: 20px;
      background: color-mix(in srgb, var(--card) 92%, transparent);
      box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent);
      color: var(--fg);
      font: 15px/1.5 "SFMono-Regular", "Menlo", "Consolas", monospace;
      white-space: pre-wrap;
      overflow: auto;
    }
    .shortcode-mermaid.is-rendered .shortcode-mermaid-definition {
      display: none;
    }
    .shortcode-mermaid-caption {
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .agenda-slide ol {
      margin: 22px 0 0;
      padding-left: 28px;
      font-size: 28px;
      line-height: 1.45;
    }
    .agenda-slide li {
      margin-bottom: 14px;
      padding-left: 8px;
    }
    .image-slide {
      display: grid;
      align-content: start;
      height: 100%;
    }
    .image-shell {
      display: grid;
      gap: 20px;
      align-content: start;
    }
    .image-slide p:has(img) {
      margin: 0;
    }
    .image-slide img {
      width: 100%;
      max-height: 52vh;
      object-fit: cover;
      border-radius: 24px;
      box-shadow: 0 20px 48px var(--shadow);
    }
    .two-column-slide {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 40px;
      align-content: start;
      height: 100%;
    }
    .two-column-slide .column {
      min-width: 0;
      padding: 22px 24px;
      border-radius: 24px;
      background: color-mix(in srgb, var(--card) 90%, var(--accent) 10%);
      border: 1px solid color-mix(in srgb, var(--accent) 14%, transparent);
    }
    .two-column-slide .column > :first-child {
      margin-top: 0;
    }
    .media-split-slide {
      display: grid;
      grid-template-columns: minmax(0, 1.05fr) minmax(0, 0.95fr);
      gap: 36px;
      align-items: center;
      height: 100%;
    }
    .media-split-slide.media-left {
      grid-template-areas: "media content";
    }
    .media-split-slide.media-right {
      grid-template-areas: "content media";
    }
    .media-pane {
      grid-area: media;
      min-width: 0;
    }
    .content-pane {
      grid-area: content;
      min-width: 0;
    }
    .media-pane p {
      margin: 0;
    }
    .media-pane img {
      width: 100%;
      max-height: 58vh;
      object-fit: cover;
      border-radius: 26px;
      box-shadow: 0 24px 56px var(--shadow);
    }
    .content-pane > :first-child {
      margin-top: 0;
    }
    .content-pane > :last-child {
      margin-bottom: 0;
    }
    .quote-slide {
      display: grid;
      gap: 28px;
      align-content: center;
      height: 100%;
    }
    .quote-shell {
      max-width: 880px;
      padding: 24px 0;
    }
    .quote-slide blockquote {
      margin: 0;
      padding-left: 28px;
      border-left: 4px solid var(--accent);
      font-size: 42px;
      line-height: 1.2;
      color: var(--fg);
    }
    .quote-slide p:last-child {
      margin: 0;
      font: 16px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .metric-slide {
      display: grid;
      gap: 18px;
      align-content: center;
      height: 100%;
      text-align: center;
    }
    .metric-shell {
      padding: 40px 48px;
      border-radius: 28px;
      background: linear-gradient(180deg, color-mix(in srgb, var(--accent) 12%, transparent), color-mix(in srgb, var(--card) 96%, white 4%));
      border: 1px solid color-mix(in srgb, var(--accent) 24%, transparent);
      box-shadow: 0 24px 56px var(--shadow);
    }
    .metric-slide h1 {
      margin: 0;
      font-size: 132px;
      line-height: 0.95;
      color: var(--accent);
    }
    .metric-slide p {
      margin: 0;
    }
    .metric-slide p:first-of-type {
      font-size: 28px;
    }
    .metric-slide p:last-of-type {
      max-width: 560px;
      margin-inline: auto;
      color: var(--muted);
    }
    .closing-slide {
      display: grid;
      place-items: center;
      height: 100%;
      text-align: center;
    }
    .closing-shell {
      background:
        radial-gradient(circle at top, color-mix(in srgb, var(--accent) 18%, transparent), transparent 45%),
        linear-gradient(180deg, color-mix(in srgb, var(--card) 92%, white 8%), color-mix(in srgb, var(--card) 98%, white 2%));
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      border-radius: 28px;
      padding: 40px 42px;
      box-sizing: border-box;
      box-shadow: 0 24px 56px var(--shadow);
    }
    .closing-shell h1 {
      font-size: 72px;
      margin-bottom: 18px;
    }
    .closing-shell p {
      max-width: 540px;
      margin-inline: auto;
      color: var(--muted);
      font-size: 22px;
      line-height: 1.4;
    }
    @page {
      size: 13.333in 7.5in;
      margin: 0;
    }
  </style>
</head>
<body>
  <main>
    <div class="deck">
      {{ $root := . }}
      {{ range $slide := .Slides }}
      <section class="slide{{ if $slide.ImageHintClass }} {{ $slide.ImageHintClass }}{{ end }}"{{ if $slide.StyleAttr }} style="{{ $slide.StyleAttr }}"{{ end }}>
        {{ if $slide.IsDraft }}<div class="draft-badge">Draft</div>{{ end }}
        {{ template "deck-logo" (dict "Root" $root "Slide" $slide) }}
        {{ $slide.Body }}
        {{ if $slide.ImageCaption }}<div class="image-caption">{{ $slide.ImageCaption }}</div>{{ end }}
        {{ template "deck-footer" (dict "Root" $root "Slide" $slide) }}
      </section>
      {{ end }}
    </div>
  </main>
  <script type="module">
    const diagrams = Array.from(document.querySelectorAll('.shortcode-mermaid'));
    if (diagrams.length) {
      try {
        const mermaidModule = await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs');
        const mermaid = mermaidModule.default;
        const mermaidTheme = getComputedStyle(document.documentElement).colorScheme === 'dark' ? 'dark' : 'default';
        mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', theme: mermaidTheme });
        for (const [diagramIndex, diagram] of diagrams.entries()) {
          const definition = diagram.querySelector('.shortcode-mermaid-definition')?.textContent?.trim();
          const target = diagram.querySelector('.shortcode-mermaid-render');
          if (!definition || !target) continue;
          const { svg } = await mermaid.render('margo-print-mermaid-' + diagramIndex, definition);
          target.innerHTML = svg;
          diagram.classList.add('is-rendered');
        }
      } catch (error) {
        console.warn('Mermaid render failed', error);
      }
    }
  </script>
  {{ .Snippets.BodyEnd }}
</body>
</html>
`
}

func defaultThemeSlideLayout() string {
	return `<div class="slide-shell content-slide">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body prose-body">{{ .Body }}</div>
</div>
`
}

func defaultThemeTitleLayout() string {
	return `<div class="slide-shell title-slide">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body title-stack">
    {{ .Body }}
  </div>
</div>
`
}

func defaultThemeSectionLayout() string {
	return `<div class="slide-shell section-slide">
  <div class="slide-meta">Section</div>
  <div class="slide-body section-stack">
    <h1>{{ .Slide.Title }}</h1>
  </div>
</div>
`
}

func defaultThemeAgendaLayout() string {
	return `<div class="slide-shell agenda-layout">
  <div class="slide-meta">Agenda</div>
  <div class="slide-body agenda-slide prose-body">
    {{ .Body }}
  </div>
</div>
`
}

func defaultThemeQuoteLayout() string {
	return `<div class="slide-shell quote-layout">
  <div class="slide-meta">Quote</div>
  <div class="slide-body quote-slide">
    <div class="quote-shell">
      {{ .Body }}
    </div>
  </div>
</div>
`
}

func defaultThemeImageLayout() string {
	return `<div class="slide-shell image-layout">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body image-slide">
    <div class="image-shell prose-body">
      {{ .Body }}
    </div>
  </div>
</div>
`
}

func defaultThemeTwoColumnLayout() string {
	return `<div class="slide-shell split-layout">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body two-column-slide prose-body">
    <div class="column">
      {{ if .BodyColumns }}{{ index .BodyColumns 0 }}{{ else }}{{ .Body }}{{ end }}
    </div>
    <div class="column">
      {{ if gt (len .BodyColumns) 1 }}{{ index .BodyColumns 1 }}{{ end }}
    </div>
  </div>
</div>
`
}

func defaultThemeMediaRightLayout() string {
	return `<div class="slide-shell split-layout">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body media-split-slide media-right">
    <div class="content-pane prose-body">
      {{ .LeadContent }}
    </div>
    <div class="media-pane">
      {{ .LeadMedia }}
    </div>
  </div>
</div>
`
}

func defaultThemeMediaLeftLayout() string {
	return `<div class="slide-shell split-layout">
  {{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
  <div class="slide-meta">{{ .Slide.Title }}</div>
  <div class="slide-body media-split-slide media-left">
    <div class="media-pane">
      {{ .LeadMedia }}
    </div>
    <div class="content-pane prose-body">
      {{ .LeadContent }}
    </div>
  </div>
</div>
`
}

func defaultThemeMetricLayout() string {
	return `<div class="slide-shell metric-layout">
  <div class="slide-meta">Metric</div>
  <div class="slide-body metric-slide">
    <div class="metric-shell">
      {{ .Body }}
    </div>
  </div>
</div>
`
}

func defaultThemeClosingLayout() string {
	return `<div class="slide-shell closing-layout">
  <div class="slide-meta">Closing</div>
  <div class="slide-body closing-slide">
    <div class="closing-shell">
      {{ .Body }}
    </div>
  </div>
</div>
`
}

func defaultThemeStyles() string {
	return `/* Theme-local styles can be added here later. */
`
}

func yamlString(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "Untitled Deck"
	}
	return value
}
