package scaffold

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type DeckOptions struct {
	Name      string
	TargetDir string
}

func CreateDeck(opts DeckOptions) error {
	if opts.Name == "" {
		return errors.New("deck name is required")
	}
	if opts.TargetDir == "" {
		return errors.New("target directory is required")
	}

	targetDir, err := filepath.Abs(opts.TargetDir)
	if err != nil {
		return fmt.Errorf("resolve target directory: %w", err)
	}

	files := map[string]string{
		"margo.yaml": scaffoldConfig(opts.Name),
		filepath.Join("slides", "01-title", "index.md"):          slideTitle(opts.Name),
		filepath.Join("slides", "02-why", "index.md"):            slideWhy(),
		filepath.Join("archetypes", "default", "archetype.yaml"): defaultArchetypeMetadata(),
		filepath.Join("archetypes", "title", "archetype.yaml"):   titleArchetypeMetadata(),
		filepath.Join("archetypes", "section", "archetype.yaml"): sectionArchetypeMetadata(),
		filepath.Join("archetypes", "agenda", "archetype.yaml"):  agendaArchetypeMetadata(),
		filepath.Join("archetypes", "quote", "archetype.yaml"):   quoteArchetypeMetadata(),
		filepath.Join("archetypes", "metric", "archetype.yaml"):  metricArchetypeMetadata(),
		filepath.Join("archetypes", "closing", "archetype.yaml"): closingArchetypeMetadata(),
		filepath.Join("shortcodes", "eyebrow.html"):              defaultDeckEyebrowShortcode(),
	}
	for path, content := range ThemeFiles("default", true) {
		files[path] = content
	}

	dirs := []string{
		"assets",
		filepath.Join("layouts"),
		filepath.Join("slides"),
		filepath.Join("themes"),
		filepath.Join("archetypes"),
		filepath.Join("shortcodes"),
	}

	if err := ensureCreatable(targetDir, files); err != nil {
		return err
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(targetDir, dir), 0o755); err != nil {
			return fmt.Errorf("create directory %q: %w", dir, err)
		}
	}

	for relativePath, content := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("create parent directory for %q: %w", relativePath, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %q: %w", relativePath, err)
		}
	}

	return nil
}

func ensureCreatable(targetDir string, files map[string]string) error {
	if info, err := os.Stat(targetDir); err == nil {
		if !info.IsDir() {
			return fmt.Errorf("target path exists and is not a directory: %s", targetDir)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat target directory %q: %w", targetDir, err)
	}

	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return fmt.Errorf("create target directory %q: %w", targetDir, err)
	}

	for relativePath := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if _, err := os.Stat(fullPath); err == nil {
			return fmt.Errorf("target file already exists: %s", fullPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat target file %q: %w", fullPath, err)
		}
	}

	return nil
}

func scaffoldConfig(deckName string) string {
	return fmt.Sprintf(`version: 1

deck:
  title: %s
  description: Starter deck generated by margo
  language: en
  logo: MARGO
  footer: Internal Strategy Review

theme:
  name: default
  color_mode: light
  typography: editorial
  accent_color: "#8f6f33"

outputs:
  html: true
  pdf: true
`, yamlString(deckName))
}

func slideTitle(deckName string) string {
	return fmt.Sprintf(`---
title: %s
order: 1
layout: title
---

# %s

Build beautiful slides from Markdown.
`, yamlString(deckName), yamlString(deckName))
}

func slideWhy() string {
	return `---
title: Why Margo
order: 2
layout: content
---

{{< eyebrow label="Why this exists" />}}

- Markdown-first authoring
- Hugo-like project structure
- HTML-first output with PDF next
`
}

func defaultArchetypeMetadata() string {
	return `name: default
description: Default slide archetype
default_layout: content
default_type: basic
`
}

func sectionArchetypeMetadata() string {
	return `name: section
description: Explicit section divider slide
default_layout: section
default_type: section
`
}

func titleArchetypeMetadata() string {
	return `name: title
description: Title or opening slide
default_layout: title
default_type: title
`
}

func agendaArchetypeMetadata() string {
	return `name: agenda
description: Agenda slide with ordered talking points
default_layout: agenda
default_type: agenda
`
}

func quoteArchetypeMetadata() string {
	return `name: quote
description: Quote slide with attribution
default_layout: quote
default_type: quote
`
}

func metricArchetypeMetadata() string {
	return `name: metric
description: Single key metric or KPI slide
default_layout: metric
default_type: metric
`
}

func closingArchetypeMetadata() string {
	return `name: closing
description: Closing or thank-you slide
default_layout: closing
default_type: closing
`
}

func defaultThemeMetadata() string {
	return `name: default
version: 0.1.0
description: Default Margo starter theme
config_options:
  - name: color_mode
    type: string
    description: Light or dark presentation mode
    default: light
  - name: typography
    type: string
    description: Typography preset for deck tone
    default: editorial
  - name: accent_color
    type: string
    description: Accent color used for emphasis
    default: "#8f6f33"
`
}

func ThemeFiles(themeName string, includeStyles bool) map[string]string {
	files := map[string]string{
		filepath.Join("themes", themeName, "theme.yaml"):                    defaultThemeMetadataWithName(themeName),
		filepath.Join("themes", themeName, "layouts", "deck.html"):          defaultThemeDeckLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-agenda.html"):  defaultThemeAgendaLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-closing.html"): defaultThemeClosingLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-default.html"): defaultThemeSlideLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-metric.html"):  defaultThemeMetricLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-quote.html"):   defaultThemeQuoteLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-section.html"): defaultThemeSectionLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-title.html"):   defaultThemeTitleLayout(),
		filepath.Join("themes", themeName, "shortcodes", "callout.html"):    defaultThemeCalloutShortcode(),
	}
	if includeStyles {
		files[filepath.Join("themes", themeName, "assets", "theme.css")] = defaultThemeStyles()
	}
	return files
}

func defaultThemeMetadataWithName(themeName string) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0
description: Default Margo starter theme
config_options:
  - name: color_mode
    type: string
    description: Light or dark presentation mode
    default: light
  - name: typography
    type: string
    description: Typography preset for deck tone
    default: editorial
  - name: accent_color
    type: string
    description: Accent color used for emphasis
    default: "#8f6f33"
`, yamlString(themeName))
}

func defaultDeckEyebrowShortcode() string {
	return `<div class="section-meta">{{ index .Params "label" }}</div>
`
}

func defaultThemeCalloutShortcode() string {
	return `<div class="callout callout-{{ index .Params "tone" }}">
  {{ .Inner }}
</div>
`
}

func defaultThemeDeckLayout() string {
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ .Deck.Title }}</title>
  <style>
    :root {
      color-scheme: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}dark{{ else }}light{{ end }};
      --accent: {{ themeOption .ThemeOptions "accent_color" "#8f6f33" }};
      --bg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#131617{{ else }}#f4f1ea{{ end }};
      --fg: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#f3efe8{{ else }}#1c1a17{{ end }};
      --muted: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#a9b0ac{{ else }}#6d655c{{ end }};
      --card: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}#1c2123{{ else }}#fffdf9{{ end }};
      --shadow: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}rgba(0, 0, 0, 0.28){{ else }}rgba(28, 26, 23, 0.12){{ end }};
    }
    body {
      margin: 0;
      font-family: {{ if eq (themeOption .ThemeOptions "typography" "editorial") "executive" }}"Avenir Next", "Helvetica Neue", sans-serif{{ else }}"Iowan Old Style", Georgia, serif{{ end }};
      background: {{ if eq (themeOption .ThemeOptions "color_mode" "light") "dark" }}linear-gradient(180deg, #0f1213 0%, #1a2022 100%){{ else }}linear-gradient(180deg, #ebe5d8 0%, #f7f3ea 100%){{ end }};
      color: var(--fg);
    }
    main {
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 24px;
      box-sizing: border-box;
    }
    .deck {
      width: min(1200px, 100%);
      aspect-ratio: 16 / 9;
      background: var(--card);
      box-shadow: 0 24px 80px var(--shadow);
      overflow: hidden;
      position: relative;
    }
    .slide {
      display: none;
      height: 100%;
      padding: 72px;
      box-sizing: border-box;
      position: relative;
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
    }
    .slide::before {
      content: "";
      position: absolute;
      inset: 0;
      background: var(--margo-background-overlay, transparent);
      opacity: var(--margo-background-opacity, 1);
      pointer-events: none;
    }
    .slide.active {
      display: block;
    }
    .slide > * {
      position: relative;
      z-index: 1;
    }
    .deck-logo {
      position: absolute;
      top: 24px;
      right: 28px;
      font: 12px/1 sans-serif;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .deck-footer {
      position: absolute;
      left: 72px;
      bottom: 28px;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .slide-meta {
      font-size: 14px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
      margin-bottom: 24px;
    }
    .section-meta {
      margin-bottom: 12px;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--accent);
    }
    .draft-badge {
      display: inline-block;
      margin-bottom: 18px;
      padding: 6px 10px;
      border: 1px solid currentColor;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #8a3b12;
      background: #f7dcc9;
    }
    .slide-body h1,
    .slide-body h2,
    .slide-body p,
    .slide-body ul {
      margin: 0 0 16px;
    }
    .slide-body ul {
      padding-left: 24px;
    }
    .slide-body img {
      max-width: 100%;
      height: auto;
      border-radius: 18px;
      object-position: var(--margo-image-position, center);
    }
    .slide.image-fit-contain .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: contain;
    }
    .slide.image-fit-cover .slide-body img {
      width: 100%;
      max-height: 48vh;
      object-fit: cover;
    }
    .image-caption {
      margin-top: 14px;
      font: 12px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .agenda-slide ol {
      margin: 32px 0 0;
      padding-left: 28px;
      font-size: 28px;
      line-height: 1.45;
    }
    .agenda-slide li {
      margin-bottom: 14px;
      padding-left: 8px;
    }
    .quote-slide {
      display: grid;
      gap: 28px;
      align-content: center;
      height: 100%;
    }
    .quote-shell {
      max-width: 880px;
    }
    .quote-slide blockquote {
      margin: 0;
      padding-left: 28px;
      border-left: 4px solid var(--accent);
      font-size: 42px;
      line-height: 1.2;
      color: var(--fg);
    }
    .quote-slide p:last-child {
      margin: 0;
      font: 16px/1.3 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
    }
    .metric-slide {
      display: grid;
      gap: 18px;
      align-content: center;
      height: 100%;
      text-align: center;
    }
    .metric-shell {
      padding: 40px 48px;
      border-radius: 28px;
      background: linear-gradient(180deg, color-mix(in srgb, var(--accent) 12%, transparent), rgba(255, 253, 249, 0.96));
      border: 1px solid color-mix(in srgb, var(--accent) 24%, transparent);
    }
    .metric-slide h1 {
      margin: 0;
      font-size: 132px;
      line-height: 0.95;
      color: var(--accent);
    }
    .metric-slide p {
      margin: 0;
    }
    .metric-slide p:first-of-type {
      font-size: 28px;
    }
    .metric-slide p:last-of-type {
      max-width: 560px;
      margin-inline: auto;
      color: var(--muted);
    }
    .closing-slide {
      display: grid;
      place-items: center;
      height: 100%;
      text-align: center;
    }
    .closing-shell {
      background:
        radial-gradient(circle at top, color-mix(in srgb, var(--accent) 18%, transparent), transparent 45%),
        linear-gradient(180deg, rgba(248, 244, 235, 0.9), rgba(255, 253, 249, 1));
      border: 1px solid color-mix(in srgb, var(--accent) 18%, transparent);
      border-radius: 28px;
      padding: 32px;
      box-sizing: border-box;
    }
    .closing-shell h1 {
      font-size: 72px;
      margin-bottom: 18px;
    }
    .closing-shell p {
      max-width: 540px;
      margin-inline: auto;
      color: var(--muted);
      font-size: 22px;
      line-height: 1.4;
    }
    .controls {
      position: absolute;
      right: 24px;
      bottom: 18px;
      color: var(--muted);
      font: 14px/1.2 sans-serif;
      display: flex;
      gap: 12px;
      align-items: center;
    }
    .pdf-export {
      border: 1px solid rgba(28, 26, 23, 0.18);
      background: rgba(255, 253, 249, 0.92);
      color: var(--fg);
      padding: 8px 12px;
      border-radius: 999px;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      cursor: pointer;
    }
    .pdf-export:hover {
      background: #fffdf9;
    }
  </style>
</head>
<body>
  <main>
    <div class="deck">
      {{ range $i, $slide := .Slides }}
      <section class="slide{{ if eq $i 0 }} active{{ end }}{{ if $slide.ImageHintClass }} {{ $slide.ImageHintClass }}{{ end }}"{{ if or $slide.BackgroundStyle $slide.ImageHintStyle }} style="{{ if $slide.BackgroundStyle }}{{ $slide.BackgroundStyle }}{{ end }}{{ if and $slide.BackgroundStyle $slide.ImageHintStyle }}; {{ end }}{{ if $slide.ImageHintStyle }}{{ $slide.ImageHintStyle }}{{ end }}"{{ end }}>
        {{ if $slide.IsDraft }}<div class="draft-badge">Draft</div>{{ end }}
        {{ if and $.Deck.Logo (not $slide.HideLogo) }}<div class="deck-logo">{{ $.Deck.Logo }}</div>{{ end }}
        {{ $slide.Body }}
        {{ if $slide.ImageCaption }}<div class="image-caption">{{ $slide.ImageCaption }}</div>{{ end }}
        {{ if and $slide.ResolvedFooterText (not $slide.HideFooter) }}<div class="deck-footer">{{ $slide.ResolvedFooterText }}</div>{{ end }}
      </section>
      {{ end }}
      <div class="controls">
        {{ if .PDFEnabled }}<button class="pdf-export" type="button" id="export-pdf">Export PDF</button>{{ end }}
        <span>Use left/right arrow keys</span>
      </div>
    </div>
  </main>
  <script>
    const slides = Array.from(document.querySelectorAll('.slide'));
    let index = 0;
    const show = (nextIndex) => {
      if (!slides.length) return;
      index = Math.max(0, Math.min(nextIndex, slides.length - 1));
      slides.forEach((slide, i) => slide.classList.toggle('active', i === index));
    };
    document.addEventListener('keydown', (event) => {
      if (event.key === 'ArrowRight' || event.key === 'PageDown') show(index + 1);
      if (event.key === 'ArrowLeft' || event.key === 'PageUp') show(index - 1);
    });
    const exportButton = document.getElementById('export-pdf');
    if (exportButton) {
      exportButton.addEventListener('click', async () => {
        try {
          const response = await fetch('/__margo/export/pdf', { method: 'POST' });
          const message = (await response.text()).trim();
          if (!response.ok) {
            throw new Error(message || 'PDF export failed');
          }
          window.alert(message || 'PDF export complete');
        } catch (error) {
          window.alert(error.message || 'PDF export failed');
        }
      });
    }
    let currentRevision = null;
    const checkRevision = async () => {
      try {
        const response = await fetch('/__margo/version', { cache: 'no-store' });
        const nextRevision = (await response.text()).trim();
        if (currentRevision === null) {
          currentRevision = nextRevision;
          return;
        }
        if (nextRevision !== currentRevision) {
          window.location.reload();
        }
      } catch (_) {}
    };
    setInterval(checkRevision, 1000);
    checkRevision();
  </script>
</body>
</html>
`
}

func defaultThemeSlideLayout() string {
	return `{{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
<div class="slide-meta">{{ .Slide.Title }}</div>
<div class="slide-body">{{ .Body }}</div>
`
}

func defaultThemeTitleLayout() string {
	return `{{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
<div class="slide-meta">{{ .Slide.Title }}</div>
<div class="slide-body">
  {{ .Body }}
</div>
`
}

func defaultThemeSectionLayout() string {
	return `<div class="slide-meta">Section</div>
<div class="slide-body">
  <h1>{{ .Slide.Title }}</h1>
</div>
`
}

func defaultThemeAgendaLayout() string {
	return `<div class="slide-meta">Agenda</div>
<div class="slide-body agenda-slide">
  {{ .Body }}
</div>
`
}

func defaultThemeQuoteLayout() string {
	return `<div class="slide-meta">Quote</div>
<div class="slide-body quote-slide">
  <div class="quote-shell">
    {{ .Body }}
  </div>
</div>
`
}

func defaultThemeMetricLayout() string {
	return `<div class="slide-meta">Metric</div>
<div class="slide-body metric-slide">
  <div class="metric-shell">
    {{ .Body }}
  </div>
</div>
`
}

func defaultThemeClosingLayout() string {
	return `<div class="slide-meta">Closing</div>
<div class="slide-body closing-slide">
  <div class="closing-shell">
    {{ .Body }}
  </div>
</div>
`
}

func defaultThemeStyles() string {
	return `/* Theme-local styles can be added here later. */
`
}

func yamlString(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "Untitled Deck"
	}
	return value
}
