package scaffold

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type DeckOptions struct {
	Name      string
	TargetDir string
}

func CreateDeck(opts DeckOptions) error {
	if opts.Name == "" {
		return errors.New("deck name is required")
	}
	if opts.TargetDir == "" {
		return errors.New("target directory is required")
	}

	targetDir, err := filepath.Abs(opts.TargetDir)
	if err != nil {
		return fmt.Errorf("resolve target directory: %w", err)
	}

	files := map[string]string{
		"margo.yaml": scaffoldConfig(opts.Name),
		filepath.Join("slides", "01-title", "index.md"):          slideTitle(opts.Name),
		filepath.Join("slides", "02-why", "index.md"):            slideWhy(),
		filepath.Join("archetypes", "default", "archetype.yaml"): defaultArchetypeMetadata(),
		filepath.Join("archetypes", "title", "archetype.yaml"):   titleArchetypeMetadata(),
		filepath.Join("archetypes", "section", "archetype.yaml"): sectionArchetypeMetadata(),
		filepath.Join("shortcodes", "eyebrow.html"):              defaultDeckEyebrowShortcode(),
	}
	for path, content := range ThemeFiles("default", true) {
		files[path] = content
	}

	dirs := []string{
		"assets",
		filepath.Join("layouts"),
		filepath.Join("slides"),
		filepath.Join("themes"),
		filepath.Join("archetypes"),
		filepath.Join("shortcodes"),
	}

	if err := ensureCreatable(targetDir, files); err != nil {
		return err
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(targetDir, dir), 0o755); err != nil {
			return fmt.Errorf("create directory %q: %w", dir, err)
		}
	}

	for relativePath, content := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("create parent directory for %q: %w", relativePath, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %q: %w", relativePath, err)
		}
	}

	return nil
}

func ensureCreatable(targetDir string, files map[string]string) error {
	if info, err := os.Stat(targetDir); err == nil {
		if !info.IsDir() {
			return fmt.Errorf("target path exists and is not a directory: %s", targetDir)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat target directory %q: %w", targetDir, err)
	}

	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return fmt.Errorf("create target directory %q: %w", targetDir, err)
	}

	for relativePath := range files {
		fullPath := filepath.Join(targetDir, relativePath)
		if _, err := os.Stat(fullPath); err == nil {
			return fmt.Errorf("target file already exists: %s", fullPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat target file %q: %w", fullPath, err)
		}
	}

	return nil
}

func scaffoldConfig(deckName string) string {
	return fmt.Sprintf(`version: 1

deck:
  title: %s
  description: Starter deck generated by margo
  language: en

theme:
  name: default

outputs:
  html: true
  pdf: true
`, yamlString(deckName))
}

func slideTitle(deckName string) string {
	return fmt.Sprintf(`---
title: %s
order: 1
layout: title
---

# %s

Build beautiful slides from Markdown.
`, yamlString(deckName), yamlString(deckName))
}

func slideWhy() string {
	return `---
title: Why Margo
order: 2
layout: content
---

{{< eyebrow label="Why this exists" />}}

- Markdown-first authoring
- Hugo-like project structure
- HTML-first output with PDF next
`
}

func defaultArchetypeMetadata() string {
	return `name: default
description: Default slide archetype
default_layout: content
default_type: basic
`
}

func sectionArchetypeMetadata() string {
	return `name: section
description: Explicit section divider slide
default_layout: section
default_type: section
`
}

func titleArchetypeMetadata() string {
	return `name: title
description: Title or opening slide
default_layout: title
default_type: title
`
}

func defaultThemeMetadata() string {
	return `name: default
version: 0.1.0
description: Default Margo starter theme
`
}

func ThemeFiles(themeName string, includeStyles bool) map[string]string {
	files := map[string]string{
		filepath.Join("themes", themeName, "theme.yaml"):                    defaultThemeMetadataWithName(themeName),
		filepath.Join("themes", themeName, "layouts", "deck.html"):          defaultThemeDeckLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-default.html"): defaultThemeSlideLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-section.html"): defaultThemeSectionLayout(),
		filepath.Join("themes", themeName, "layouts", "slide-title.html"):   defaultThemeTitleLayout(),
		filepath.Join("themes", themeName, "shortcodes", "callout.html"):    defaultThemeCalloutShortcode(),
	}
	if includeStyles {
		files[filepath.Join("themes", themeName, "assets", "theme.css")] = defaultThemeStyles()
	}
	return files
}

func defaultThemeMetadataWithName(themeName string) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0
description: Default Margo starter theme
`, yamlString(themeName))
}

func defaultDeckEyebrowShortcode() string {
	return `<div class="section-meta">{{ index .Params "label" }}</div>
`
}

func defaultThemeCalloutShortcode() string {
	return `<div class="callout callout-{{ index .Params "tone" }}">
  {{ .Inner }}
</div>
`
}

func defaultThemeDeckLayout() string {
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ .Deck.Title }}</title>
  <style>
    :root {
      color-scheme: light dark;
      --bg: #f4f1ea;
      --fg: #1c1a17;
      --muted: #6d655c;
      --card: #fffdf9;
      --shadow: rgba(28, 26, 23, 0.12);
    }
    body {
      margin: 0;
      font-family: Georgia, "Times New Roman", serif;
      background: linear-gradient(180deg, #ebe5d8 0%, #f7f3ea 100%);
      color: var(--fg);
    }
    main {
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 24px;
      box-sizing: border-box;
    }
    .deck {
      width: min(1200px, 100%);
      aspect-ratio: 16 / 9;
      background: var(--card);
      box-shadow: 0 24px 80px var(--shadow);
      overflow: hidden;
      position: relative;
    }
    .slide {
      display: none;
      height: 100%;
      padding: 72px;
      box-sizing: border-box;
    }
    .slide.active {
      display: block;
    }
    .slide-meta {
      font-size: 14px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--muted);
      margin-bottom: 24px;
    }
    .section-meta {
      margin-bottom: 12px;
      font: 12px/1.2 sans-serif;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: #8f6f33;
    }
    .draft-badge {
      display: inline-block;
      margin-bottom: 18px;
      padding: 6px 10px;
      border: 1px solid currentColor;
      font: 12px/1 sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #8a3b12;
      background: #f7dcc9;
    }
    .slide-body h1,
    .slide-body h2,
    .slide-body p,
    .slide-body ul {
      margin: 0 0 16px;
    }
    .slide-body ul {
      padding-left: 24px;
    }
    .controls {
      position: absolute;
      right: 24px;
      bottom: 18px;
      color: var(--muted);
      font: 14px/1.2 sans-serif;
    }
  </style>
</head>
<body>
  <main>
    <div class="deck">
      {{ range $i, $slide := .Slides }}
      <section class="slide{{ if eq $i 0 }} active{{ end }}">
        {{ if $slide.IsDraft }}<div class="draft-badge">Draft</div>{{ end }}
        {{ $slide.Body }}
      </section>
      {{ end }}
      <div class="controls">Use left/right arrow keys</div>
    </div>
  </main>
  <script>
    const slides = Array.from(document.querySelectorAll('.slide'));
    let index = 0;
    const show = (nextIndex) => {
      if (!slides.length) return;
      index = Math.max(0, Math.min(nextIndex, slides.length - 1));
      slides.forEach((slide, i) => slide.classList.toggle('active', i === index));
    };
    document.addEventListener('keydown', (event) => {
      if (event.key === 'ArrowRight' || event.key === 'PageDown') show(index + 1);
      if (event.key === 'ArrowLeft' || event.key === 'PageUp') show(index - 1);
    });
    let currentRevision = null;
    const checkRevision = async () => {
      try {
        const response = await fetch('/__margo/version', { cache: 'no-store' });
        const nextRevision = (await response.text()).trim();
        if (currentRevision === null) {
          currentRevision = nextRevision;
          return;
        }
        if (nextRevision !== currentRevision) {
          window.location.reload();
        }
      } catch (_) {}
    };
    setInterval(checkRevision, 1000);
    checkRevision();
  </script>
</body>
</html>
`
}

func defaultThemeSlideLayout() string {
	return `{{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
<div class="slide-meta">{{ .Slide.Title }}</div>
<div class="slide-body">{{ .Body }}</div>
`
}

func defaultThemeTitleLayout() string {
	return `{{ if .SectionTitle }}<div class="section-meta">{{ .SectionTitle }}</div>{{ end }}
<div class="slide-meta">{{ .Slide.Title }}</div>
<div class="slide-body">
  {{ .Body }}
</div>
`
}

func defaultThemeSectionLayout() string {
	return `<div class="slide-meta">Section</div>
<div class="slide-body">
  <h1>{{ .Slide.Title }}</h1>
</div>
`
}

func defaultThemeStyles() string {
	return `/* Theme-local styles can be added here later. */
`
}

func yamlString(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "Untitled Deck"
	}
	return value
}
